### ISSUE TITLE
Failure on Plan Stage

### ISSUE THREAD

**Issue by cdeli** [tevert/Vsts-Release-Terraform#3]
Running "Plan" causes failure. With leaving out a step for "init" prior to it generates a blank error.

When running "init" followed by "plan" you recieve the following error on the plan stage:

`erraform version:`
`Terraform v0.11.1`
`+ provider.azurerm v0.3.3`
`+ provider.random v1.1.0`
`Running: terraform plan`
`[0m[1mRefreshing Terraform state in-memory prior to plan...[0m'`
`The refreshed state will be used to calculate this plan, but will not be persisted to local or remote state storage. `
`[0m`
`------------------------------------------------------------------------`
`[31m`
`[1m[31mError: [0m[0m[1mError running plan: 1 error(s) occurred:`
`* provider.azurerm: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.[0m`
`[0m[0m[0m`
`Terraform failed to execute. Error:`
`End of Task Terraform`

**Comment by tevert** [comment]
Hi cdeli! 

When running Terraform in a CI environment, the recommended practice is to configure a service principal - see the azurerm provider docs: https://www.terraform.io/docs/providers/azurerm/

Note that in the example there, they plop the connection info right in `tf` files. This is probably a security no-no for most people, so I'd instead configure those using `variable`s, and then passing those in as additional command line args (https://www.terraform.io/intro/getting-started/variables.html).

Then, when you're passing the values in, pass them as VSTS Release variables. When you setup the VSTS variables, mark them secure to hide the values.

Let me know if there's problems with that approach!

**Comment by cdeli** [comment]
Yep that worked. I can't believe I forgot that in my build. I just added the variables right into the file, I will go through and make them in VSTS now that I know this works.

Also how do you get the "yes" to translate into the apply stage?

**Comment by cdeli** [comment]
Nevermind, fat fingered my switch to apply it. Thanks for the help!

**Comment by tevert** [comment]
No worries, glad it worked! 

```
> terraform --help apply
.
.
.
 -auto-approve          Skip interactive approval of plan before applying.
.
.
.
```
