### ISSUE TITLE
Passing Variables

### ISSUE THREAD

**Issue by cdeli** [tevert/Vsts-Release-Terraform#4]
Do you have any examples on how to pass the variables? I have the variables defined in the library and linked to the build job but they seem to not be referencing. I added the following line to attempt to call them:

`-var 'subscription_id=vars' -var 'client_id=vars' -var 'client_secret=vars' -var 'tenant_id=vars'`

and flipped it around as well to:

`-var 'vars=subscription_id' -var 'vars=client_id' -var 'vars=client_secret' -var 'vars=tenant_id'`

My code I have tried using

`variable subscription_id {`
`        description = "words in here"`
`}`

as well as:

`provider "azurerm" {`
`  subscription_id = "${var.subscription_id}"`
`  client_id       = "${var.client_id}"`
`  client_secret   = "${var.client_secret}"`
`  tenant_id       = "${var.tenant_id}"`
`}`

but cannot seem to get the variables to take. Get an error telling me: 

`- provider config 'azurerm': unknown variable referenced: 'subscription_id'; define it with a 'variable' block`
`- provider config 'azurerm': unknown variable referenced: 'client_id'; define it with a 'variable' block`
`- provider config 'azurerm': unknown variable referenced: 'client_secret'; define it with a 'variable' block`
`- provider config 'azurerm': unknown variable referenced: 'tenant_id'; define it with a 'variable' block`

Each time I run it.

**Comment by tevert** [comment]
Terraform is fairly pedantic in how it handles variables. Each one has to be explicitly declared as a variable before it can be referenced. Then you'll get another error until you've either provided a value or a `default_value` on the variable. 

So you'll need:
```hcl
variable "subscription_id" { default_value = "this isn't a secret, you can probably just include this in the source file for simplicity" }
variable "client_id" { default_value = "also not secret" }
variable "client_secret" {}
variable "tenant_id" { default_value = "also not secret" }

provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id = "${var.client_id}"
  client_secret = "${var.client_secret}"
  tenant_id = "${var.tenant_id}"
}
```

And you'll call it with `terraform plan -var "client_secret=abc123"`


EDIT for posterity: It should actually be
```hcl
variable "subscription_id" { default = "this isn't a secret, you can probably just include this in the source file for simplicity" }
variable "client_id" { default = "also not secret" }
variable "client_secret" {}
variable "tenant_id" { default = "also not secret" }
```

**Comment by giuliov** [comment]
Why not simply using VSTS variables? If they start with `TF_VAR_` they are magically taken up by Terraform (see https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name)

**Comment by tevert** [comment]
That's another great option for passing, but I suspect cdeli's issue is not having them all declared (based on his error message).

**Comment by giuliov** [comment]
Also in the case of the Azure RM provider, you can use `ARM_SUBSCRIPTION_ID`, `ARM_CLIENT_ID`, `ARM_CLIENT_SECRET`, `ARM_TENANT_ID` avoiding explicit Terraform variables (see https://www.terraform.io/docs/providers/azurerm/index.html#testing).

**Comment by tevert** [comment]
I was under the impression those were only used in acceptance testing situations? I haven't tried outside of that.

**Comment by cdeli** [comment]
How would I use the ARM variables in this? I am pretty new to using anything in VSTS for pipelines as well as using Terraform. 

I am trying to just pass them from the library, where each is declared, into the build profile but it seems that is not working as I would like it too.

**Comment by tevert** [comment]
If by "ARM variables" you're referring to the variables giuliov mentioned, those would be set in the variables tab of the VSTS build/release, and they should be exposed to the build/release process as environment variables.

**Comment by cdeli** [comment]
Right. I had all 4 of them listed per the names for Terraform (subscription_id, client_id, client_secret, and tenant_id) as well as the values for each of them. Where would I put the names for "ARM_SUBSCRIPTION_ID" and the like though? Would those be the names of the variables in VSTS or the names of the variables in my terraform script?

I also tried doing your suggjestion @tevert with putting all the variables except client secret, right into the code. I am getting a single error that way with it saying:

`Running: terraform init -var "client_secret=MyClientSecret`
`There are some problems with the configuration, described below.`
`The Terraform configuration must be valid before initialization so that`
`Terraform can determine which modules and providers need to be installed.`
`Error loading D:\a\1\s\Learning\Linux\terraformLnxTestVM.tf: 1 error(s) occurred:`
`* variable[subscription_id]: invalid key: default_value`

Literally just a copy and paste on your post above, syntax all seems right from what I can tell.

**Comment by tevert** [comment]
Ahhhh that's my fault - it should be `default` not `default_value`.

```hcl
variable "subscription_id" { default = "this isn't a secret, you can probably just include this in the source file for simplicity" }
variable "client_id" { default = "also not secret" }
variable "client_secret" {}
variable "tenant_id" { default = "also not secret" }
```

You shouldn't need ARM_SUBSCRIPTION_ID or the others. So far as I know, those are only used when running acceptance tests of the provider itself.

**Comment by cdeli** [comment]
No problem, happens to all of us.

Looks like I have it working now. my new argument reads "<action> -var "vars=ARM_CLIENT_SECRET" and I linked my library and made the item in it "ARM_CLIENT_SECRET" with my ID in the other box. All three steps (Init, Plan, Apply) all succeeded and pulled that secret properly.

If you don't mind I may write up a how-to on this for people on my level and initiate a pull request to you so theirs a guide in here about this.

Appreciate the help on getting this working.

**Comment by tevert** [comment]
I'd say the vast majority of what we've worked through here has more to do with the Azure provider itself. If you want to embellish or add to their [docs](https://www.terraform.io/docs/providers/azurerm/index.html), their Github is over [here](https://github.com/terraform-providers/terraform-provider-azurerm)

The goal of this extension is to be as thin a layer as possible between VSTS and Terraform. 

Glad you got it working!
