### ISSUE TITLE
Add ability to set TF_LOG

### ISSUE THREAD

**Issue by scott1138** [tevert/Vsts-Release-Terraform#5]
I'm new the the VSTS deployment process but pretty good with PowerShell.  It should be pretty easy to add by implementing a  picklist with the different TF_LOG options defaulting to ERROR and then adding something like this to the invoke-terraform:

$tf_log = Get-VstsInput -Name tf_log
[Environment]::SetEnvironmentVariable("TF_LOG", $tf_log, "Process")

I would do this myself, but I am not entirely sure how to go about it.

**Comment by tevert** [comment]
Hey @scott1138 - 

I've done a bit of testing and this actually works already by providing `TF_LOG` as a release variable. The Powershell runner task that this inherits from automatically pulls in release variables as environment variables. 

![image](https://user-images.githubusercontent.com/6742531/40023284-2a7ae9e0-5790-11e8-8df7-50d148164639.png)

Re-open and let me know if you're having more problems with that!

**Comment by scott1138** [comment]
Awesome, thanks for the info!

Regards,

Scott Heath

Lead DevOps Engineer

t 1 214 445 1441<tel:+1%20214%20445%201441> | m 1 972 273 0752 | <tel:+1%20972%20273%200752> freeman.com<http://freeman.com/>
